[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "auto-configparser"
version = "1.1.1"
dependencies = [
    'importlib-metadata; python_version>="3.9"',
    'pydantic~=2.12.5'
]